fix: [main] CI/CD 수정

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -43,9 +43,6 @@ jobs:
           # EC2에 도커 허브 로그인
           ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "sudo docker login -u '${{ secrets.DOCKER_HUB_USERNAME }}' -p '${{ secrets.DOCKER_HUB_PASSWORD }}'"
 
-          # Docker 자원 정리
-          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "sudo docker system prune -a -f"
-
           # 새로운 이미지를 풀
           ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/blog-api-app:latest"
 
@@ -54,40 +51,38 @@ jobs:
           sudo docker run -d --name app_new --network travelplan_travelplan_blog-net -p 3001:3000 --env-file /home/ubuntu/TravelPlan/.env ${{ secrets.DOCKER_HUB_USERNAME }}/blog-api-app:latest
           "
 
-          # Nginx 설정 파일 수정
+          # 헬스 체크
           ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
-          sudo sed -i 's/server app:3000;/server app_new:3001;/' /etc/nginx/nginx.conf
-          sudo sed -i 's/server app:3000;/server app_new:3001;/' /etc/nginx/sites-enabled/default
-          "
+          if sudo docker inspect --format='{{json .State.Health.Status}}' app_new | grep -q 'healthy'; then
+            # Nginx 설정 파일 수정
+            sudo sed -i 's/server app:3000;/server app_new:3001;/' /etc/nginx/nginx.conf
+            sudo sed -i 's/server app:3000;/server app_new:3001;/' /etc/nginx/sites-enabled/default
 
-          # Nginx 설정 파일 테스트 및 재시작
-          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
-          if sudo nginx -t; then
-            sudo systemctl reload nginx
+            # Nginx 설정 테스트 및 재시작
+            if sudo nginx -t; then
+              sudo systemctl reload nginx
+            else
+              echo 'Nginx configuration test failed! Rolling back...'
+              sudo docker stop app_new
+              sudo docker rm app_new
+              exit 1
+            fi
+
+            # 기존 컨테이너 중지 및 제거
+            CONTAINER_ID=\$(sudo docker ps -q --filter 'name=app');
+            if [ -n "\$CONTAINER_ID" ]; then
+              sudo docker stop \$CONTAINER_ID;  # 기존 컨테이너 중지
+              sudo docker rm \$CONTAINER_ID;    # 기존 컨테이너 제거
+            fi
+
+            # 새로운 컨테이너 이름 변경
+            sudo docker rename app_new app
           else
-            echo 'Nginx configuration test failed!'
+            echo 'New container is not healthy! Aborting deployment.'
+            sudo docker stop app_new
+            sudo docker rm app_new
             exit 1
           fi
-          "
-
-          # 기존 컨테이너 중지 및 제거
-          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
-          CONTAINER_ID=\$(sudo docker ps -q --filter 'name=app');
-          if [ -n \"\$CONTAINER_ID\" ]; then
-            sudo docker stop \$CONTAINER_ID;  # 기존 컨테이너 중지
-            sudo docker rm \$CONTAINER_ID;    # 기존 컨테이너 제거
-          fi
-          "
-
-          # 새로운 컨테이너 이름 변경
-          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
-          sudo docker rename app_new app
-          "
-
-          # Nginx 설정 다시 변경
-          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
-          sudo sed -i 's/server app_new:3001;/server app:3000;/' /etc/nginx/nginx.conf
-          sudo sed -i 's/server app_new:3001;/server app:3000;/' /etc/nginx/sites-enabled/default
           "
 
           # 최종 Nginx 설정 테스트 및 재시작
@@ -95,7 +90,7 @@ jobs:
           if sudo nginx -t; then
             sudo systemctl reload nginx
           else
-            echo 'Nginx final configuration test failed!'
+            echo 'Final Nginx configuration test failed!'
             exit 1
           fi
           "
